language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - python manage.py collectstatic --noinput
  - ls -a playacamp/
  - ls -a playacamp/staticfiles/
  - ls -a staticfiles/
  - python manage.py test
